global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    cluster: 'smart-alarm-prod'
    environment: 'production'

rule_files:
  - "/etc/prometheus/alerts/*.yml"
  - "/etc/prometheus/rules/*.yml"
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      timeout: 10s
      api_version: v2

scrape_configs:
