global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Smart Alarm API
  - job_name: 'smartalarm-api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # AI Service
  - job_name: 'smartalarm-ai-service'
    static_configs:
      - targets: ['ai-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Alarm Service
  - job_name: 'smartalarm-alarm-service'
    static_configs:
      - targets: ['alarm-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Integration Service
  - job_name: 'smartalarm-integration-service'
    static_configs:
      - targets: ['integration-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
