global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@smartalarm.com'
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'smart-alarm-team'
  routes:
    - match:
        severity: critical
      receiver: 'smart-alarm-critical'
      group_wait: 5s
      repeat_interval: 30m
    - match:
        severity: warning
      receiver: 'smart-alarm-warning'
      repeat_interval: 2h
    - match:
        team: smart-alarm
        alertname: SLOAvailabilityBreached
      receiver: 'slo-breach-critical'
      group_wait: 0s
      repeat_interval: 15m
    - match:
        team: smart-alarm
        alertname: SLOLatencyBreached
      receiver: 'slo-breach-critical'
      group_wait: 0s
      repeat_interval: 15m
    - match:
        team: smart-alarm
        alertname: SLOErrorRateBreached
      receiver: 'slo-breach-critical'
      group_wait: 0s
      repeat_interval: 15m

receivers:
  - name: 'smart-alarm-team'
    email_configs:
      - to: 'team@smartalarm.com'
        subject: '[SmartAlarm] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Runbook: {{ .Annotations.runbook }}
          Labels: {{ .Labels }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#smartalarm-alerts'
        title: '[SmartAlarm] {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert*: {{ .Annotations.summary }}
          *Description*: {{ .Annotations.description }}
          *Runbook*: {{ .Annotations.runbook }}
          *Labels*: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}

  - name: 'smart-alarm-critical'
    email_configs:
      - to: 'oncall@smartalarm.com'
        subject: '[CRITICAL] SmartAlarm Alert: {{ .GroupLabels.alertname }}'
        body: |
          CRITICAL ALERT - IMMEDIATE ACTION REQUIRED
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Runbook: {{ .Annotations.runbook }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#smartalarm-critical'
        title: '🚨 [CRITICAL] SmartAlarm Alert'
        color: 'danger'
        text: |
          {{ range .Alerts }}
          *🚨 CRITICAL ALERT - IMMEDIATE ACTION REQUIRED*
          
          *Alert*: {{ .Annotations.summary }}
          *Description*: {{ .Annotations.description }}
          *Runbook*: <{{ .Annotations.runbook }}|View Runbook>
          *Service*: {{ .Labels.service }}
          *Instance*: {{ .Labels.instance }}
          *Started*: {{ .StartsAt }}
          {{ end }}
    pagerduty_configs:
      - routing_key: 'YOUR_PAGERDUTY_INTEGRATION_KEY'
        description: '{{ .GroupLabels.alertname }}: {{ .GroupLabels.service }}'
        details:
          alert: '{{ .GroupLabels.alertname }}'
          service: '{{ .GroupLabels.service }}'
          instance: '{{ .GroupLabels.instance }}'
          description: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

  - name: 'smart-alarm-warning'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#smartalarm-alerts'
        title: '⚠️ [WARNING] SmartAlarm Alert'
        color: 'warning'
        text: |
          {{ range .Alerts }}
          *⚠️ Warning Alert*
          
          *Alert*: {{ .Annotations.summary }}
          *Description*: {{ .Annotations.description }}
          *Runbook*: <{{ .Annotations.runbook }}|View Runbook>
          *Service*: {{ .Labels.service }}
          *Instance*: {{ .Labels.instance }}
          {{ end }}

  - name: 'slo-breach-critical'
    email_configs:
      - to: 'sre@smartalarm.com,product@smartalarm.com'
        subject: '[SLO BREACH] SmartAlarm SLI/SLO Violation'
        body: |
          SLO BREACH DETECTED - SERVICE LEVEL OBJECTIVES VIOLATED
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Runbook: {{ .Annotations.runbook }}
          Service: {{ .Labels.service }}
          SLO Impact: This may affect customer experience and business SLAs
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#smartalarm-slo'
        title: '🎯 [SLO BREACH] Service Level Objective Violated'
        color: 'danger'
        text: |
          {{ range .Alerts }}
          *🎯 SLO BREACH - Customer Impact Possible*
          
          *Alert*: {{ .Annotations.summary }}
          *Description*: {{ .Annotations.description }}
          *Runbook*: <{{ .Annotations.runbook }}|View Runbook>
          *Service*: {{ .Labels.service }}
          *Business Impact*: This may affect customer experience and SLAs
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service', 'instance']

  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '(HighErrorRate|HighResponseTime|DatabaseConnectionsHigh)'
    equal: ['service', 'instance']
